const STORAGE_KEY='liam_companion_v1';
const state=loadState();
let currentTab='fixture';
let editingId=null;

function defaultState(){return{settings:{season:'2026/27',club:'Heart of Midlothian',homeVenue:'Tynecastle Park',nationalTeam:'England'},draft:newDraft(),matches:[]}}
function newDraft(){return{id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:new Date().toISOString().slice(0,10),competition:'Scottish Premiership',stage:'League',opponent:'',homeAway:'Home',venue:'',teamPos:'',oppPos:'',context:'',goals:[],assists:[],teamGoals:'',oppGoals:'',status:'START',subIn:'',subOut:'',rating:'',shots:'',sot:'',dribbles:'',dribblePct:'',offsides:'',possLost:'',sprintKm:'',disallowed:'0',yellow:'0',red:'0',motm:'0',notes:'',storyTag:''}}
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||defaultState()}catch{return defaultState()}}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));updateStatus()}
function val(id){return document.getElementById(id).value}
function setVal(id,v){const el=document.getElementById(id);if(el)el.value=v??''}
function num(v){return v===''||v===null||v===undefined?'':Number(v)}
function minuteToBase(v){if(!v)return 0;const p=String(v).split('+').map(Number);return(p[0]||0)+(p[1]||0)}
function calcMinutes(m){if(!['START','SUB'].includes(m.status))return 0;const entry=m.status==='START'?0:minuteToBase(m.subIn);const exit=m.subOut?minuteToBase(m.subOut):90;return Math.max(0,exit-entry)}
function result(m){const a=Number(m.teamGoals),b=Number(m.oppGoals);return a>b?'W':a<b?'L':'D'}
function venueFor(m){if(m.homeAway==='Neutral')return m.venue||'';return m.homeAway==='Home'?state.settings.homeVenue:''}
function monthName(date){if(!date)return'';return new Date(date+'T00:00:00').toLocaleString('en',{month:'long'})}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function updateStatus(){const d=state.draft;const has=d.opponent||d.goals.length||d.assists.length||d.teamGoals!=='';document.getElementById('draftStatus').textContent=has?'Draft active':'No active match'}

function populate(){const d=state.draft;for(const [id,key] of Object.entries({date:'date',competition:'competition',stage:'stage',opponent:'opponent',venue:'venue',teamPos:'teamPos',oppPos:'oppPos',context:'context',teamGoals:'teamGoals',oppGoals:'oppGoals',status:'status',subIn:'subIn',subOut:'subOut',rating:'rating',shots:'shots',sot:'sot',dribbles:'dribbles',dribblePct:'dribblePct',offsides:'offsides',possLost:'possLost',sprintKm:'sprintKm',disallowed:'disallowed',yellow:'yellow',red:'red',motm:'motm',notes:'notes',storyTag:'storyTag'}))setVal(id,d[key]);
  document.querySelectorAll('#haButtons button').forEach(b=>b.classList.toggle('active',b.dataset.value===d.homeAway));document.getElementById('venueField').style.display=d.homeAway==='Neutral'?'block':'none';
  setVal('settingSeason',state.settings.season);setVal('settingClub',state.settings.club);setVal('settingHomeVenue',state.settings.homeVenue);setVal('settingNational',state.settings.nationalTeam);renderEvents();renderRecords();updateStatus();
}
function pullDraft(){const d=state.draft;for(const [id,key] of Object.entries({date:'date',competition:'competition',stage:'stage',opponent:'opponent',venue:'venue',teamPos:'teamPos',oppPos:'oppPos',context:'context',teamGoals:'teamGoals',oppGoals:'oppGoals',status:'status',subIn:'subIn',subOut:'subOut',rating:'rating',shots:'shots',sot:'sot',dribbles:'dribbles',dribblePct:'dribblePct',offsides:'offsides',possLost:'possLost',sprintKm:'sprintKm',disallowed:'disallowed',yellow:'yellow',red:'red',motm:'motm',notes:'notes',storyTag:'storyTag'}))d[key]=val(id);persist()}
function switchTab(id){currentTab=id;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id));window.scrollTo({top:0,behavior:'smooth'})}

document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{pullDraft();switchTab(b.dataset.tab)}));
document.querySelectorAll('#haButtons button').forEach(b=>b.addEventListener('click',()=>{state.draft.homeAway=b.dataset.value;document.querySelectorAll('#haButtons button').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('venueField').style.display=b.dataset.value==='Neutral'?'block':'none';persist()}));

document.getElementById('saveFixture').onclick=()=>{pullDraft();if(!state.draft.opponent)return showToast('Opponent is required');showToast('Pre-match details saved');switchTab('events')};
document.getElementById('saveDraft').onclick=()=>{pullDraft();showToast('Draft saved locally')};
document.getElementById('nextTab').onclick=()=>{pullDraft();const order=['fixture','events','performance','records'];switchTab(order[Math.min(order.indexOf(currentTab)+1,3)])};

function addEvent(type){const minute=prompt(`${type==='goal'?'Goal':'Assist'} minute (e.g. 18, 45+2, 90+5)`);if(!minute)return;state.draft[type==='goal'?'goals':'assists'].push(String(minute).trim());state.draft[type==='goal'?'goals':'assists'].sort((a,b)=>minuteToBase(a)-minuteToBase(b));persist();renderEvents()}
document.getElementById('addGoal').onclick=()=>addEvent('goal');document.getElementById('addAssist').onclick=()=>addEvent('assist');
function renderEvents(){const list=document.getElementById('eventList');const events=[...state.draft.goals.map((m,i)=>({type:'Goal',m,i,key:'goals'})),...state.draft.assists.map((m,i)=>({type:'Assist',m,i,key:'assists'}))].sort((a,b)=>minuteToBase(a.m)-minuteToBase(b.m));list.innerHTML=events.length?events.map(e=>`<div class="event-item"><strong>${e.m}'</strong><small>${e.type}</small><button data-key="${e.key}" data-i="${e.i}">×</button></div>`).join(''):'<div class="empty">No goals or assists recorded yet.</div>';list.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.draft[b.dataset.key].splice(Number(b.dataset.i),1);persist();renderEvents()})}

function validateMatch(d){if(!d.date)return'Date is required';if(!d.opponent)return'Opponent is required';if(d.teamGoals===''||d.oppGoals==='')return'Final score is required';if(['START','SUB'].includes(d.status)&&d.rating==='')return'Rating is required for an appearance';if(d.status==='SUB'&&!d.subIn)return'Subbed-in minute is required';return''}
document.getElementById('saveMatch').onclick=()=>{pullDraft();const err=validateMatch(state.draft);if(err)return showToast(err);const saved={...state.draft,id:editingId||state.draft.id,savedAt:new Date().toISOString()};const idx=state.matches.findIndex(m=>m.id===saved.id);if(idx>=0)state.matches[idx]=saved;else state.matches.push(saved);state.matches.sort((a,b)=>a.date.localeCompare(b.date));state.draft=newDraft();editingId=null;persist();populate();switchTab('records');showToast('Match saved')};

function renderRecords(){const matches=state.matches;document.getElementById('matchCount').textContent=`${matches.length} match${matches.length===1?'':'es'}`;const apps=matches.filter(m=>['START','SUB'].includes(m.status));const goals=apps.reduce((s,m)=>s+m.goals.length,0),assists=apps.reduce((s,m)=>s+m.assists.length,0),mins=apps.reduce((s,m)=>s+calcMinutes(m),0);const ratingRows=apps.filter(m=>Number(m.rating)>0);const avg=ratingRows.length?(ratingRows.reduce((s,m)=>s+Number(m.rating)*Math.max(calcMinutes(m),1),0)/ratingRows.reduce((s,m)=>s+Math.max(calcMinutes(m),1),0)).toFixed(2):'—';document.getElementById('summary').innerHTML=[["Apps",apps.length],["Goals",goals],["Assists",assists],["G/A",goals+assists],["Minutes",mins],["Weighted avg",avg]].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');const list=document.getElementById('matchList');list.innerHTML=matches.length?[...matches].reverse().map(m=>`<div class="match-card"><div class="meta"><span>${m.date} · ${m.competition}</span><span>${m.status}</span></div><h4>${state.settings.club} ${m.teamGoals}–${m.oppGoals} ${m.opponent}</h4><p>${m.goals.length}G · ${m.assists.length}A · ${m.rating||'—'} rating · ${calcMinutes(m)} min</p><div class="actions"><button data-edit="${m.id}">Edit</button><button data-delete="${m.id}">Delete</button></div></div>`).join(''):'<div class="empty">No matches saved yet.</div>';list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const m=matches.find(x=>x.id===b.dataset.edit);state.draft=JSON.parse(JSON.stringify(m));editingId=m.id;persist();populate();switchTab('fixture');showToast('Editing saved match')});list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Delete this match?')){state.matches=matches.filter(x=>x.id!==b.dataset.delete);persist();renderRecords()}})}

function csvEscape(v){const s=String(v??'');return/[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
function download(name,text,type='text/plain'){const blob=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
const teamHeaders=['Match_No','Date','Season','Month','Club','Competition','Competition_Stage','Venue','Home_Away','Opponent','Team_Position_Before','Opponent_Position_Before','Team_Goals','Opponent_Goals','Result','Liam_Status','Liam_Started','Liam_Minutes','Liam_Goals','Liam_Assists','Liam_Rating','Goal_Minutes','Shots','Shots_On_Target','Disallowed_Goal','Yellow','Red','Notes','Story_Tag','Match_Context','Competition_Type','International_Stage','Cap_No','International_Goal_No','Assist_Minutes','Dribbles','Dribble_Success_Pct','Offsides','Possession_Lost','Distance_Sprinted_Km'];
const appHeaders=['Match_No','Date','Season','Month','Club','Competition','Competition_Stage','Venue','Home_Away','Opponent','Team_Position_Before','Opponent_Position_Before','Team_Goals','Opponent_Goals','Result','Liam_Started','Liam_Minutes','Liam_Goals','Liam_Assists','Liam_Rating','Goal_Minutes','Shots','Shots_On_Target','Disallowed_Goal','Yellow','Red','MOTM','Notes','Story_Tag','Match_Context','Competition_Type','International_Stage','Cap_No','International_Goal_No','Assist_Minutes','Dribbles','Dribble_Success_Pct','Offsides','Possession_Lost','Distance_Sprinted_Km'];
function rowFor(m,i,team){const started=m.status==='START'?'Y':'N';const compType=m.competition.includes('International')||m.competition.includes('Euro')||m.competition.includes('World')?'International':'Club';const base={Match_No:i+1,Date:m.date,Season:state.settings.season,Month:monthName(m.date),Club:compType==='International'?state.settings.nationalTeam:state.settings.club,Competition:m.competition,Competition_Stage:m.stage,Venue:venueFor(m),Home_Away:m.homeAway,Opponent:m.opponent,Team_Position_Before:m.teamPos,Opponent_Position_Before:m.oppPos,Team_Goals:m.teamGoals,Opponent_Goals:m.oppGoals,Result:result(m),Liam_Status:m.status,Liam_Started:started,Liam_Minutes:calcMinutes(m),Liam_Goals:m.goals.length,Liam_Assists:m.assists.length,Liam_Rating:m.rating,Goal_Minutes:m.goals.join(';'),Assist_Minutes:m.assists.join(';'),Shots:m.shots,Shots_On_Target:m.sot,Disallowed_Goal:m.disallowed,Yellow:m.yellow,Red:m.red,MOTM:m.motm,Notes:m.notes,Story_Tag:m.storyTag,Match_Context:m.context,Competition_Type:compType,International_Stage:compType==='International'?m.stage:'',Cap_No:'',International_Goal_No:'',Dribbles:m.dribbles,Dribble_Success_Pct:m.dribblePct,Offsides:m.offsides,Possession_Lost:m.possLost,Distance_Sprinted_Km:m.sprintKm};return base}
function exportCsv(team){const headers=team?teamHeaders:appHeaders;const source=team?state.matches:state.matches.filter(m=>['START','SUB'].includes(m.status));const lines=[headers.join(',')];source.forEach((m,i)=>{const r=rowFor(m,i,team);lines.push(headers.map(h=>csvEscape(r[h])).join(','))});download(team?'current_season_team_matches.csv':'current_season_matches.csv',lines.join('\n'),'text/csv')}
document.getElementById('exportTeamCsv').onclick=()=>exportCsv(true);document.getElementById('exportAppsCsv').onclick=()=>exportCsv(false);document.getElementById('exportJson').onclick=()=>download('liam_companion_backup.json',JSON.stringify(state,null,2),'application/json');
document.getElementById('importJson').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const imported=JSON.parse(r.result);Object.assign(state,imported);persist();populate();showToast('Backup imported')}catch{showToast('Invalid JSON backup')}};r.readAsText(f)};
document.getElementById('clearAll').onclick=()=>{if(confirm('Clear all matches and the active draft?')){Object.assign(state,defaultState());persist();populate()}};
document.getElementById('saveSettings').onclick=()=>{state.settings={season:val('settingSeason'),club:val('settingClub'),homeVenue:val('settingHomeVenue'),nationalTeam:val('settingNational')};persist();document.querySelector('.brand p').textContent=`${state.settings.season} · ${state.settings.club}`;showToast('Settings saved')};

window.addEventListener('beforeunload',pullDraft);if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('service-worker.js');populate();
