const STORAGE_KEY='liam_companion_v3_1_5B';
const LEGACY_STORAGE_KEYS=['liam_companion_v3','liam_companion_v2','liam_companion_v1'];
const SCHEMA_VERSION='1.5B';
const APP_VERSION='3.1.5B-migration-fix';
const DEFAULT_COMPETITIONS=[
  {name:'Scottish Premiership',type:'Club'},
  {name:'Scottish Cup',type:'Club'},
  {name:'Scottish League Cup',type:'Club'},
  {name:'UEFA Conference League',type:'Club'},
  {name:'International Friendly',type:'International'},
  {name:'Euro Qualifier',type:'International'},
  {name:'Euro Cup',type:'International'},
  {name:'World Cup Qualifier',type:'International'},
  {name:'International Cup',type:'International'},
  {name:'Other',type:'Club'}
];
let state;
let currentTab='fixture';
let editingId=null;
let startupLoadSource='default';
let startupMigrationError='';

function seasonStartYear(season){const match=String(season||'').match(/^(\d{4})\s*\//);return match?Number(match[1]):new Date().getFullYear()}
function seasonDefaultDate(season){return `${seasonStartYear(season)}-07-01`}
function addDays(dateString,days){const parts=String(dateString||'').split('-').map(Number);if(parts.length!==3||parts.some(Number.isNaN))return dateString;const date=new Date(Date.UTC(parts[0],parts[1]-1,parts[2]));date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)}
function uuid(){return crypto.randomUUID?crypto.randomUUID():`match-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function machineHomeAway(value){const raw=String(value||'').trim().toUpperCase();return raw==='HOME'?'H':raw==='AWAY'?'A':raw==='NEUTRAL'?'N':['H','A','N'].includes(raw)?raw:'H'}
function displayHomeAway(value){return{H:'Home',A:'Away',N:'Neutral'}[machineHomeAway(value)]}
function machineCompType(value){return String(value||'Club').toUpperCase()==='INTERNATIONAL'?'INTERNATIONAL':'CLUB'}
function displayCompType(value){return machineCompType(value)==='INTERNATIONAL'?'International':'Club'}
function newDraft(settings={season:'2037/38'},dateOverride=''){const id=uuid();return{id,Match_ID:id,Season:settings.season,date:dateOverride||seasonDefaultDate(settings.season),competition:'Scottish Premiership',competitionType:'Club',stage:'League',opponent:'',homeAway:'H',venue:'',teamPos:'',oppPos:'',context:'',goals:[],assists:[],teamGoals:'',oppGoals:'',status:'START',subIn:'',subOut:'',rating:'',shots:'',shotAccuracy:'',shotsOnTarget:'',dribbles:'',dribblePct:'',offsides:'',possLost:'',sprintKm:'',disallowed:'0',yellow:'0',red:'0',motm:'0',notes:'',storyTag:''}}
function defaultState(){const settings={season:'2037/38',club:'Heart of Midlothian',homeVenue:'Tynecastle Park',nationalTeam:'England',competitions:DEFAULT_COMPETITIONS.map(x=>({...x}))};const defaultDate=seasonDefaultDate(settings.season);return{schemaVersion:SCHEMA_VERSION,settings,competitions:settings.competitions,datePreference:{type:'season_changed',at:new Date().toISOString(),date:defaultDate},draft:newDraft(settings,defaultDate),matches:[],migrationNotes:[]}}
function migrateMatch(m,settings){const source=m||{};const out={...newDraft(settings||{season:'2037/38'}),...source};out.id=source.id||source.Match_ID||uuid();out.Match_ID=source.Match_ID||source.matchId||source.id||out.id;out.Season=source.Season||source.season||settings?.season||'2037/38';out.homeAway=machineHomeAway(out.homeAway);if(out.shotAccuracy===''&&out.sot!==''&&out.shots!==''&&Number(out.shots)>0)out.shotAccuracy=Math.round(Number(out.sot)/Number(out.shots)*100);if(out.shotsOnTarget===''&&out.Shots_On_Target!=='')out.shotsOnTarget=out.Shots_On_Target||'';if(!out.competitionType)out.competitionType=(settings?.competitions||DEFAULT_COMPETITIONS).find(c=>c.name===out.competition)?.type||'Club';if(!Array.isArray(out.goals))out.goals=[];if(!Array.isArray(out.assists))out.assists=[];return out}
function migrateState(raw){const base=defaultState();const settings={...base.settings,...(raw?.settings||{})};const rawCompetitions=Array.isArray(raw?.competitions)?raw.competitions:raw?.settings?.competitions;if(Array.isArray(rawCompetitions)&&rawCompetitions.length)settings.competitions=rawCompetitions.map(c=>({name:c.name,type:displayCompType(c.type)}));else settings.competitions=DEFAULT_COMPETITIONS.map(x=>({...x}));const migrationNotes=[...(Array.isArray(raw?.migrationNotes)?raw.migrationNotes:[])];const matches=Array.isArray(raw?.matches)?raw.matches.map(m=>{const hadSeason=Boolean(m?.Season||m?.season);const migrated=migrateMatch(m,settings);if(!hadSeason)migrationNotes.push(`Match ${migrated.Match_ID} assigned inferred Season ${migrated.Season} during v${SCHEMA_VERSION} migration.`);return migrated}):[];let datePreference=raw?.datePreference;if(!datePreference||!datePreference.date){const last=matches.length?[...matches].sort((a,b)=>(a.savedAt||a.date).localeCompare(b.savedAt||b.date)).at(-1):null;datePreference=last?{type:'match_saved',at:last.savedAt||new Date().toISOString(),date:addDays(last.date,2)}:{type:'season_changed',at:new Date().toISOString(),date:seasonDefaultDate(settings.season)}}const draft=migrateMatch(raw?.draft||newDraft(settings,datePreference.date),settings);if(isDraftEmpty(draft))draft.date=datePreference.date;return{...base,...raw,schemaVersion:SCHEMA_VERSION,settings,competitions:settings.competitions,datePreference,draft,matches,migrationNotes}}
function hasCustomSettings(s){const d=defaultState().settings;return ['season','club','homeVenue','nationalTeam'].some(k=>String(s?.settings?.[k]||'')!==String(d[k]||''))||(Array.isArray(s?.settings?.competitions)&&JSON.stringify(s.settings.competitions)!==JSON.stringify(d.competitions))}
function hasUserData(s){return Array.isArray(s?.matches)&&s.matches.length>0||s?.draft&&!isDraftEmpty(s.draft)||hasCustomSettings(s)}
function validateLoadedState(s){if(!s||typeof s!=='object')throw new Error('state is not an object');if(!s.settings||typeof s.settings!=='object')throw new Error('settings missing');if(!Array.isArray(s.settings.competitions))throw new Error('competitions missing');if(!Array.isArray(s.matches))throw new Error('matches missing');const ids=new Set();s.matches.forEach((m,i)=>{if(!m.id)throw new Error(`match ${i+1} missing internal id`);if(!m.Match_ID)throw new Error(`match ${i+1} missing Match_ID`);if(!m.Season)throw new Error(`match ${i+1} missing Season`);if(ids.has(m.Match_ID))throw new Error(`duplicate Match_ID ${m.Match_ID}`);ids.add(m.Match_ID)});return true}
function parseStoredState(key){const raw=localStorage.getItem(key);if(!raw)return null;return migrateState(JSON.parse(raw))}
function saveMigratedState(nextState){validateLoadedState(nextState);localStorage.setItem(STORAGE_KEY,JSON.stringify(nextState));}
function loadState(){startupLoadSource='default';startupMigrationError='';try{const current=parseStoredState(STORAGE_KEY);if(current){validateLoadedState(current);if(hasUserData(current)){startupLoadSource=STORAGE_KEY;return current}}}catch(error){console.error(`Could not load ${STORAGE_KEY}`,error);startupMigrationError=`Current 1.5B storage was invalid: ${error.message}`;}
  for(const key of LEGACY_STORAGE_KEYS){try{const migrated=parseStoredState(key);if(!migrated)continue;validateLoadedState(migrated);if(!hasUserData(migrated))continue;saveMigratedState(migrated);startupLoadSource=key;startupMigrationError='';return migrated}catch(error){console.error(`Could not migrate ${key}`,error);startupMigrationError=`Could not migrate ${key}: ${error.message}`;return {...defaultState(),migrationError:startupMigrationError}}}
  return defaultState()}
state=loadState();
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));updateStatus()}
function persistStartupState(){if(startupMigrationError){showToast(startupMigrationError);return}if(startupLoadSource==='default'||startupLoadSource===STORAGE_KEY)return;persist()}
function val(id){return document.getElementById(id).value}
function setVal(id,v){const el=document.getElementById(id);if(el)el.value=v??''}
function minuteToBase(v){if(!v)return 0;const p=String(v).split('+').map(Number);return(p[0]||0)+(p[1]||0)}
function calcMinutes(m){if(!['START','SUB'].includes(m.status))return 0;const entry=m.status==='START'?0:minuteToBase(m.subIn);const exit=m.subOut?minuteToBase(m.subOut):90;return Math.max(0,exit-entry)}
function result(m){const a=Number(m.teamGoals),b=Number(m.oppGoals);return a>b?'W':a<b?'L':'D'}
function venueFor(m){const ha=machineHomeAway(m.homeAway);if(ha==='N')return m.venue||'';return ha==='H'?state.settings.homeVenue:''}
function monthName(date){if(!date)return'';return new Date(date+'T00:00:00').toLocaleString('en',{month:'long'})}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function updateStatus(){const d=state.draft;const has=d.opponent||d.goals.length||d.assists.length||d.teamGoals!=='';document.getElementById('draftStatus').textContent=has?'Draft active':'No active match'}
function competitionTypeFor(name){return state?.settings?.competitions?.find(c=>c.name===name)?.type||'Club'}
function isDraftEmpty(d){return !d.opponent&&!d.goals.length&&!d.assists.length&&d.teamGoals===''&&d.oppGoals===''&&!d.notes&&!d.context}
function shotsOnTarget(m){return m.shotsOnTarget??m.Shots_On_Target??''}

function renderCompetitionOptions(){const select=document.getElementById('competition');const current=state.draft.competition;const comps=[...state.settings.competitions];if(current&&!comps.some(c=>c.name===current))comps.push({name:current,type:state.draft.competitionType||'Club'});select.innerHTML=comps.map(c=>`<option value="${escapeHtml(c.name)}">${escapeHtml(c.name)}</option>`).join('');select.value=current||comps[0]?.name||'';updateCompetitionHint()}
function updateCompetitionHint(){const type=competitionTypeFor(val('competition'));document.getElementById('competitionTypeHint').textContent=`${displayCompType(type)} competition`;state.draft.competitionType=displayCompType(type)}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function renderCompetitionSettings(){const list=document.getElementById('competitionSettingsList');list.innerHTML=state.settings.competitions.map((c,i)=>`<div class="settings-item"><strong>${escapeHtml(c.name)}</strong><small>${c.type}</small><button data-remove-competition="${i}">Remove</button></div>`).join('');list.querySelectorAll('[data-remove-competition]').forEach(b=>b.onclick=()=>{if(state.settings.competitions.length<=1)return showToast('Keep at least one tournament');const removed=state.settings.competitions.splice(Number(b.dataset.removeCompetition),1)[0];if(state.draft.competition===removed.name){state.draft.competition=state.settings.competitions[0].name;state.draft.competitionType=state.settings.competitions[0].type}persist();renderCompetitionSettings();renderCompetitionOptions()})}

function populate(){const d=state.draft;renderCompetitionOptions();for(const [id,key] of Object.entries({date:'date',competition:'competition',stage:'stage',opponent:'opponent',venue:'venue',teamPos:'teamPos',oppPos:'oppPos',context:'context',teamGoals:'teamGoals',oppGoals:'oppGoals',status:'status',subIn:'subIn',subOut:'subOut',rating:'rating',shots:'shots',shotAccuracy:'shotAccuracy',shotsOnTarget:'shotsOnTarget',dribbles:'dribbles',dribblePct:'dribblePct',offsides:'offsides',possLost:'possLost',sprintKm:'sprintKm',disallowed:'disallowed',yellow:'yellow',red:'red',motm:'motm',notes:'notes',storyTag:'storyTag'}))setVal(id,d[key]);
  const ha=machineHomeAway(d.homeAway);document.querySelectorAll('#haButtons button').forEach(b=>b.classList.toggle('active',b.dataset.value===ha));document.getElementById('venueField').style.display=ha==='N'?'block':'none';
  setVal('settingSeason',state.settings.season);setVal('settingClub',state.settings.club);setVal('settingHomeVenue',state.settings.homeVenue);setVal('settingNational',state.settings.nationalTeam);setVal('exportSeason',state.settings.season);renderCompetitionSettings();renderEvents();renderRecords();updateStatus();updateCompetitionHint();document.querySelector('.brand p').textContent=`${state.settings.season} · ${state.settings.club} · schema ${SCHEMA_VERSION}`}
function pullDraft(){const d=state.draft;for(const [id,key] of Object.entries({date:'date',competition:'competition',stage:'stage',opponent:'opponent',venue:'venue',teamPos:'teamPos',oppPos:'oppPos',context:'context',teamGoals:'teamGoals',oppGoals:'oppGoals',status:'status',subIn:'subIn',subOut:'subOut',rating:'rating',shots:'shots',shotAccuracy:'shotAccuracy',shotsOnTarget:'shotsOnTarget',dribbles:'dribbles',dribblePct:'dribblePct',offsides:'offsides',possLost:'possLost',sprintKm:'sprintKm',disallowed:'disallowed',yellow:'yellow',red:'red',motm:'motm',notes:'notes',storyTag:'storyTag'}))d[key]=val(id);d.homeAway=machineHomeAway(d.homeAway);d.competitionType=displayCompType(competitionTypeFor(d.competition));persist()}
function switchTab(id){currentTab=id;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id));window.scrollTo({top:0,behavior:'smooth'})}

document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{pullDraft();switchTab(b.dataset.tab)}));
document.getElementById('competition').addEventListener('change',()=>{state.draft.competition=val('competition');updateCompetitionHint();persist()});
document.querySelectorAll('#haButtons button').forEach(b=>b.addEventListener('click',()=>{state.draft.homeAway=machineHomeAway(b.dataset.value);document.querySelectorAll('#haButtons button').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('venueField').style.display=state.draft.homeAway==='N'?'block':'none';persist()}));

document.getElementById('saveFixture').onclick=()=>{pullDraft();if(!state.draft.opponent)return showToast('Opponent is required');showToast('Pre-match details saved');switchTab('events')};
document.getElementById('saveDraft').onclick=()=>{pullDraft();showToast('Draft saved locally')};
document.getElementById('nextTab').onclick=()=>{pullDraft();const order=['fixture','events','performance','records'];switchTab(order[Math.min(order.indexOf(currentTab)+1,3)])};

function addEvent(type){const minute=prompt(`${type==='goal'?'Goal':'Assist'} minute (e.g. 18, 45+2, 90+5)`);if(!minute)return;state.draft[type==='goal'?'goals':'assists'].push(String(minute).trim());state.draft[type==='goal'?'goals':'assists'].sort((a,b)=>minuteToBase(a)-minuteToBase(b));persist();renderEvents()}
document.getElementById('addGoal').onclick=()=>addEvent('goal');document.getElementById('addAssist').onclick=()=>addEvent('assist');
function renderEvents(){const list=document.getElementById('eventList');const events=[...state.draft.goals.map((m,i)=>({type:'Goal',m,i,key:'goals'})),...state.draft.assists.map((m,i)=>({type:'Assist',m,i,key:'assists'}))].sort((a,b)=>minuteToBase(a.m)-minuteToBase(b.m));list.innerHTML=events.length?events.map(e=>`<div class="event-item"><strong>${e.m}'</strong><small>${e.type}</small><button data-key="${e.key}" data-i="${e.i}">×</button></div>`).join(''):'<div class="empty">No goals or assists recorded yet.</div>';list.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.draft[b.dataset.key].splice(Number(b.dataset.i),1);persist();renderEvents()})}

function validateMatch(d){if(!d.date)return'Date is required';if(!d.opponent)return'Opponent is required';if(d.teamGoals===''||d.oppGoals==='')return'Final score is required';if(['START','SUB'].includes(d.status)&&d.rating==='')return'Rating is required for an appearance';if(d.status==='SUB'&&!d.subIn)return'Subbed-in minute is required';return''}
document.getElementById('saveMatch').onclick=()=>{pullDraft();const err=validateMatch(state.draft);if(err)return showToast(err);const savedAt=new Date().toISOString();const existing=editingId?state.matches.find(m=>m.id===editingId):null;const stableId=existing?.Match_ID||state.draft.Match_ID||state.draft.id||uuid();const saved={...state.draft,id:editingId||state.draft.id||stableId,Match_ID:stableId,Season:existing?.Season||state.draft.Season||state.settings.season,savedAt};const idx=state.matches.findIndex(m=>m.id===saved.id);if(idx>=0)state.matches[idx]=saved;else state.matches.push(saved);state.matches.sort((a,b)=>a.date.localeCompare(b.date)||String(a.Match_ID).localeCompare(String(b.Match_ID)));const nextDate=addDays(saved.date,2);state.datePreference={type:'match_saved',at:savedAt,date:nextDate};state.draft=newDraft(state.settings,nextDate);editingId=null;persist();populate();switchTab('records');showToast(`Match saved · next date ${nextDate}`)};

function renderRecords(){const matches=state.matches;document.getElementById('matchCount').textContent=`${matches.length} match${matches.length===1?'':'es'}`;const apps=matches.filter(m=>['START','SUB'].includes(m.status));const goals=apps.reduce((s,m)=>s+m.goals.length,0),assists=apps.reduce((s,m)=>s+m.assists.length,0),mins=apps.reduce((s,m)=>s+calcMinutes(m),0);const ratingRows=apps.filter(m=>Number(m.rating)>0);const avg=ratingRows.length?(ratingRows.reduce((s,m)=>s+Number(m.rating)*Math.max(calcMinutes(m),1),0)/ratingRows.reduce((s,m)=>s+Math.max(calcMinutes(m),1),0)).toFixed(2):'—';document.getElementById('summary').innerHTML=[["Apps",apps.length],["Goals",goals],["Assists",assists],["G/A",goals+assists],["Minutes",mins],["Weighted avg",avg]].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');const list=document.getElementById('matchList');list.innerHTML=matches.length?[...matches].reverse().map(m=>`<div class="match-card"><div class="meta"><span>${m.date} · ${m.competition}</span><span>${m.status}</span></div><h4>${m.competitionType==='International'?state.settings.nationalTeam:state.settings.club} ${m.teamGoals}–${m.oppGoals} ${m.opponent}</h4><p>${m.goals.length}G · ${m.assists.length}A · ${m.rating||'—'} rating · ${calcMinutes(m)} min</p><div class="actions"><button data-edit="${m.id}">Edit</button><button data-delete="${m.id}">Delete</button></div></div>`).join(''):'<div class="empty">No matches saved yet.</div>';list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const m=matches.find(x=>x.id===b.dataset.edit);state.draft=JSON.parse(JSON.stringify(m));editingId=m.id;persist();populate();switchTab('fixture');showToast('Editing saved match')});list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Delete this match?')){state.matches=matches.filter(x=>x.id!==b.dataset.delete);persist();renderRecords()}})}

function csvEscape(v){const s=String(v??'');return/[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
function download(name,text,type='text/plain'){const blob=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
const exportHeaders=['Match_ID','Match_No','Season','Date','Club','Opponent','Competition','Competition_Type','Stage','Home_Away','Venue','Team_Position_Before','Opponent_Position_Before','Team_Goals','Opponent_Goals','Result','Liam_Status','Appearance_Status','Entry_Minute','Exit_Minute','Minutes','Goals','Goal_Minutes','Assists','Assist_Minutes','Rating','Shots','Shot_Accuracy_Pct','Shots_On_Target','Dribbles_Attempted','Dribble_Success_Pct','Offsides','Possession_Lost','Distance_Sprinted','Disallowed_Goals','Yellow','Red','MOTM','Match_Context','Story_Tag','Notes','International_Stage','Cap_Number'];
function exportSeason(){return(val('exportSeason')||state.settings.season).trim()}
function matchesForSeason(season,playerOnly=false){const rows=state.matches.filter(m=>(m.Season||state.settings.season)===season&&(!playerOnly||['START','SUB'].includes(m.status)));return rows.sort((a,b)=>String(a.date).localeCompare(String(b.date))||String(a.Match_ID||a.id).localeCompare(String(b.Match_ID||b.id)))}
function rowFor(m,i){const compType=machineCompType(m.competitionType||competitionTypeFor(m.competition));const status=m.status;const appStatus=['START','SUB'].includes(status)?status:'';return{Match_ID:m.Match_ID||m.id,Match_No:i+1,Season:m.Season||state.settings.season,Date:m.date,Club:compType==='INTERNATIONAL'?state.settings.nationalTeam:state.settings.club,Opponent:m.opponent,Competition:m.competition,Competition_Type:compType,Stage:m.stage,Home_Away:machineHomeAway(m.homeAway),Venue:venueFor(m),Team_Position_Before:m.teamPos,Opponent_Position_Before:m.oppPos,Team_Goals:m.teamGoals,Opponent_Goals:m.oppGoals,Result:result(m),Liam_Status:status,Appearance_Status:appStatus,Entry_Minute:status==='SUB'?m.subIn:'',Exit_Minute:['START','SUB'].includes(status)?m.subOut:'',Minutes:calcMinutes(m),Goals:['START','SUB'].includes(status)?m.goals.length:0,Goal_Minutes:['START','SUB'].includes(status)?m.goals.join('|'):'',Assists:['START','SUB'].includes(status)?m.assists.length:0,Assist_Minutes:['START','SUB'].includes(status)?m.assists.join('|'):'',Rating:['START','SUB'].includes(status)?m.rating:'',Shots:['START','SUB'].includes(status)?m.shots:'',Shot_Accuracy_Pct:['START','SUB'].includes(status)?m.shotAccuracy:'',Shots_On_Target:['START','SUB'].includes(status)?shotsOnTarget(m):'',Dribbles_Attempted:['START','SUB'].includes(status)?m.dribbles:'',Dribble_Success_Pct:['START','SUB'].includes(status)?m.dribblePct:'',Offsides:['START','SUB'].includes(status)?m.offsides:'',Possession_Lost:['START','SUB'].includes(status)?m.possLost:'',Distance_Sprinted:['START','SUB'].includes(status)?m.sprintKm:'',Disallowed_Goals:['START','SUB'].includes(status)?m.disallowed:'0',Yellow:m.yellow||'0',Red:m.red||'0',MOTM:m.motm||'0',Match_Context:m.context,Story_Tag:m.storyTag,Notes:m.notes,International_Stage:compType==='INTERNATIONAL'?m.stage:'',Cap_Number:m.capNumber||''}}
function csvFor(rows){const lines=[exportHeaders.join(',')];rows.forEach((m,i)=>{const r=rowFor(m,i);lines.push(exportHeaders.map(h=>csvEscape(r[h])).join(','))});return lines.join('\n')}
function duplicateIds(rows){const seen=new Set(),dupes=new Set();rows.forEach(m=>{const id=m.Match_ID||m.id;if(seen.has(id))dupes.add(id);seen.add(id)});return[...dupes]}
function exportCsv(team){pullDraft();const season=exportSeason();if(!confirm(`Export complete ${season} snapshot? CSV exports replace, not merge, dossier data.`))return;const rows=matchesForSeason(season,!team);const dupes=duplicateIds(rows);if(dupes.length)return showToast(`Duplicate Match_ID: ${dupes[0]}`);download(team?'current_season_team_matches.csv':'current_season_matches.csv',csvFor(rows),'text/csv;charset=utf-8')}
function backupState(){return{...state,schemaVersion:SCHEMA_VERSION,competitions:state.settings.competitions}}
function exportManifest(){pullDraft();const season=exportSeason();const teamRows=matchesForSeason(season,false);const playerRows=matchesForSeason(season,true);download('export_manifest.json',JSON.stringify({schemaVersion:SCHEMA_VERSION,exportedAt:new Date().toISOString(),selectedSeason:season,teamRowCount:teamRows.length,playerRowCount:playerRows.length,companionAppVersion:APP_VERSION,filenames:['current_season_team_matches.csv','current_season_matches.csv'],canonicalProjectRoot:'/Users/shubham/Documents/Liam_Dossier'},null,2),'application/json')}
document.getElementById('exportTeamCsv').onclick=()=>exportCsv(true);document.getElementById('exportAppsCsv').onclick=()=>exportCsv(false);document.getElementById('exportManifest').onclick=()=>exportManifest();document.getElementById('exportJson').onclick=()=>download('liam_companion_backup.json',JSON.stringify(backupState(),null,2),'application/json');
document.getElementById('importJson').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=migrateState(JSON.parse(r.result));persist();populate();showToast('Backup imported')}catch{showToast('Invalid JSON backup')}};r.readAsText(f)};
document.getElementById('clearAll').onclick=()=>{if(confirm('Clear all matches and the active draft?')){state=defaultState();persist();populate()}};
document.getElementById('saveSettings').onclick=()=>{pullDraft();const oldSeason=state.settings.season;const newSeason=val('settingSeason').trim()||oldSeason;state.settings={...state.settings,season:newSeason,club:val('settingClub'),homeVenue:val('settingHomeVenue'),nationalTeam:val('settingNational')};state.competitions=state.settings.competitions;if(newSeason!==oldSeason){const seasonDate=seasonDefaultDate(newSeason);state.datePreference={type:'season_changed',at:new Date().toISOString(),date:seasonDate};state.draft=newDraft(state.settings,seasonDate);editingId=null}persist();populate();showToast(newSeason!==oldSeason?'Settings saved · new season starts 1 July':'Settings saved')};
document.getElementById('addCompetition').onclick=()=>{const name=val('newCompetitionName').trim();const type=val('newCompetitionType');if(!name)return showToast('Tournament name is required');if(state.settings.competitions.some(c=>c.name.toLowerCase()===name.toLowerCase()))return showToast('Tournament already exists');state.settings.competitions.push({name,type});setVal('newCompetitionName','');persist();renderCompetitionSettings();renderCompetitionOptions();showToast('Tournament added')};

window.addEventListener('pagehide',()=>{try{pullDraft()}catch{persist()}});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){try{pullDraft()}catch{persist()}}});if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('service-worker.js');populate();persistStartupState();
